library(dplyr)
library(tidyr)

dat = read.csv("data/2024_insect_data/EDRRPatho_NHTraps_InsectData_MFD.csv")
head(dat)
dat

# the species with No.of.species > 1 are those that Marc does not ID past
# higher taxonomic levels.
dat[is.na(dat$No.of.species), "No.of.species"] = 1
head(dat)

#fill undefined taxonomic columns with NA
# could filter by the tax columns
tax_columns = c("Class", "Order", "Family", "Subfamily", "Genus", "Species")
# but lets keep it simple and just set all "" to NA
dat[dat == ""] = NA
head(dat)

dat$Trap.Code %>% unique()
dat[is.na(dat$Trap.Code),]
# there are some ext4ra lines at the bottom
dat = dat[!is.na(dat$Trap.Code),]
dat[is.na(dat$Trap.Code),]

dat$Trap.Code %>% unique()
# these are only the Durham FS office subset of sites
# we make the sample ID as "Trap.Code %m-%dd" to match
# the collated metadata "sampleID" column format
dat$Collection.Date %>% sub("/24","", .) %>% sub("/", "-", .)

dat$sampleID = paste( sub("-", ".", dat$Trap.Code), dat$Collection.Date %>% sub("/24","", .) %>% sub("/", ".", .), sep = "..")

head(dat)
dat %>% 
    filter(No.of.species == 1) %>%
    select(sampleID, all_of(tax_columns), Finest.ID, Count) %>%
    pivot_wider(names_from = sampleID, values_from = Count) 
# taxonomic IDs are not unique. We need to find out why
dat %>% 
    filter(No.of.species == 1) %>%
    select(sampleID, all_of(tax_columns), Finest.ID, Count) %>%
    pivot_wider(names_from = sampleID, values_from = Count) %>%
    group_by(Finest.ID) %>%
    summarise(n = n()) %>%
    arrange(desc(n), )
# Bee, Pseudoscorpion, and two others
# These are not the targets (i.e., Marc not morph ID expert)
# let's pull these to take a closer look
dat %>% 
    filter(No.of.species == 1) %>%
    select(sampleID, all_of(tax_columns), Finest.ID, Count) %>%
    pivot_wider(names_from = sampleID, values_from = Count) %>%
    group_by(Finest.ID) %>%
    summarise(n = n()) %>%
    filter(n > 1) %>%
    pull(Finest.ID) -> nonunique_taxa

dat[dat$Finest.ID %in% nonunique_taxa[1],]
dat[dat$Finest.ID %in% nonunique_taxa[2],]
dat[dat$Finest.ID %in% nonunique_taxa[3],]
dat[dat$Finest.ID %in% nonunique_taxa[4],]
# these all look like incidental catch based on counts of 1 and appearing in few samples overall
# we will remove
# ACTUALLY we will keep for now bc these are not the problem taxa
# if we want to filter to the target taxa we can do that later
# based on taxonomy
# Actually we will remove because they are not uniquely ID'd in table t() for NMDS

dat %>% 
    filter(No.of.species == 1 & !Finest.ID %in% nonunique_taxa) %>%
    select(sampleID, all_of(tax_columns), Finest.ID, Count) %>%
    pivot_wider(names_from = sampleID, values_from = Count) %>%
    group_by(Finest.ID) %>%
    summarise(n = n()) %>%
    arrange(desc(n), )
# still getting nonunique warning
dat |>
  dplyr::summarise(n = dplyr::n(), .by = c(Class, Order, Family, Subfamily, Genus, Species, Finest.ID, sampleID)) |>
  dplyr::filter(n > 1L) 
# it actually appears that the error is thrown by a duplicate Caterpillar entry
# in a single sample. We'll get rid of that too
dat |>
  dplyr::summarise(n = dplyr::n(), .by = c(Finest.ID, sampleID)) |>
  dplyr::filter(n > 1L) 

dat %>% 
    filter(No.of.species == 1 & !Finest.ID %in% c("Caterpillar", nonunique_taxa)) %>%
    select(sampleID, all_of(tax_columns), Finest.ID, Count) %>%
    pivot_wider(names_from = sampleID, values_from = Count) -> dat.wide
head(dat.wide)
# convert NAs to zero.
# These are generated by the pivot_wider call
dat.wide %>%
    mutate(across(where(is.numeric), ~replace_na(., 0))) -> dat.wide
head(dat.wide)

write.csv(dat.wide, "data/2024_insect_data/species_tab.csv", quote = F, row.names = F)

# write sampleIDs too to prefilter ASV_tab
# 

write.table(colnames(dat.wide[8:ncol(dat.wide)]), "data/2024_insect_data/sampleIDs.txt", quote = F, sep = "\t", row.names = F, col.names = F)

